# Generated by Django 2.2.2 on 2019-07-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(default='untitled', max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(default='untitled', max_length=128),
        ),
    ]
