# Generated by Django 2.2.2 on 2019-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_user', '0002_auto_20190727_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
