# Generated by Django 2.2.2 on 2019-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_user', '0003_auto_20190727_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='task',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.TextField(),
        ),
    ]
