# Generated by Django 2.2.2 on 2019-07-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_user', '0005_remove_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
